"""
Game data module containing predefined lists for the situation generator.
Each list contains 50 varied and whimsical options.
"""

# 50 possible characters that can present events
TARGETS = [
    # Original 15
    "Eccentric Billionaire",
    "Conspiracy Theorist",
    "Internet Meme Creator",
    "Time-traveling Investor",
    "Talking AI Assistant",
    "Mystic Fortune Teller",
    "Alien Ambassador",
    "Teenage Hacker Prodigy",
    "Underground Cult Leader",
    "Cat in a Business Suit",
    "Self-proclaimed Prophet",
    "Robotics Engineer",
    "Former Pop Star",
    "Quantum Physicist",
    "Sentient Trading Algorithm",
    
    # 35 additional options
    "Interdimensional Broker",
    "Telekinetic Day Trader",
    "Wizard Economist",
    "Cryogenically Frozen CEO",
    "Hypnotist Financial Advisor",
    "Clone Army Investor",
    "Dancing Crypto Monkey",
    "Holographic Fortune Cookie",
    "Vampire Venture Capitalist",
    "Psychic Stock Predictor",
    "Robot Butler with Investment Tips",
    "Dolphin Financial Genius",
    "Elvis Impersonator Turned Market Guru",
    "Garden Gnome Collector",
    "Sasquatch with a Business Degree",
    "Time-Traveling Renaissance Painter",
    "Space Pirate Captain",
    "Sentient Potted Plant",
    "Astral Projecting Stockbroker",
    "Ghost of a Failed Entrepreneur",
    "Professional Meme Archeologist",
    "Cryptid Currency Expert",
    "Superhero in Retirement",
    "Anthropomorphic Blockchain",
    "Amnesiac Lottery Winner",
    "Celestial Being in Disguise",
    "Escaped Zoo Animal",
    "Animated Breakfast Cereal Mascot",
    "Sock Puppet Financial Expert",
    "Immortal From The 1800s",
    "Extremely Intelligent Goldfish",
    "Cyborg From the Future",
    "Accidentally Uploaded Human Consciousness",
    "Misunderstood Supervillain",
    "Reincarnated Ancient Emperor"
]

# 50 possible areas where events occur
AREAS = [
    # Original 15
    "Secret Underground Bunker",
    "Virtual Reality Metaverse",
    "Abandoned Space Station",
    "Luxury Yacht Party",
    "Medieval Castle Converted to Office",
    "Burning Man Festival",
    "Interdimensional Portal",
    "Floating Cloud City",
    "Submarine Research Lab",
    "Haunted Mansion",
    "Dream Realm",
    "Ancient Temple",
    "Futuristic Skyscraper",
    "Alternate Timeline",
    "Rocket Launch Pad",
    
    # 35 additional options
    "Upside-Down Building",
    "Sentient Forest",
    "Inside a Quantum Computer",
    "Microscopic Trading Floor",
    "Pocket Dimension Coffee Shop",
    "Abandoned Theme Park",
    "Library of Forbidden Knowledge",
    "Pirate Ship Call Center",
    "Asteroid Mining Colony",
    "Floating Bubble City",
    "Time-Frozen Museum",
    "Recursive Holographic Simulation",
    "Telepathic Spa Retreat",
    "Indoor Waterfall Boardroom",
    "Zero-Gravity Dance Club",
    "Invisible Skyscraper",
    "Underwater Dome City",
    "Satellite Orbiting Jupiter",
    "Miniaturized Office Inside a Snowglobe",
    "Beach Made of Precious Gems",
    "Volcanic Lair",
    "Levitating Zen Garden",
    "Giant Mushroom Commune",
    "Inside a Living Organism",
    "Memory Palace Tutorial Level",
    "Repurposed Movie Set",
    "Massive Airship",
    "Giant Hamster Tube Network",
    "Perpetual Storm Eye",
    "Candy-Constructed Castle",
    "Carnival of Impossibilities",
    "Ancient Library of Alexandria",
    "Hyperdimensional Waiting Room",
    "Enchanted Shopping Mall",
    "Interstellar Rest Stop"
]

# 50 possible types of events
EVENT_TYPES = [
    # Original 15
    "Meme Coin Explosion",
    "Mysterious Blockchain Anomaly",
    "Alien Technology Discovery",
    "Time Paradox",
    "Quantum Computing Breakthrough",
    "Internet Becoming Sentient",
    "Mass Hallucination",
    "Parallel Universe Collision",
    "Interdimensional Trading Portal",
    "Pet Adoption Trend",
    "Worldwide Dancing Craze",
    "Dream-Based Currency Launch",
    "Telepathic Trading",
    "Crypto-powered Space Colony",
    "Digital Apocalypse",
    
    # 35 additional options
    "Spontaneous Mass Levitation",
    "Time Loop Glitch",
    "Sentient Emoji Uprising",
    "Accidental Universe Creation",
    "Viral Cat Video Market Crash",
    "Collective Consciousness Upload",
    "Rogue AI Minting Spree",
    "Reverse Gravity Incident",
    "Memory Trading Platform Launch",
    "Interspecies Negotiation Summit",
    "Holographic Celebrity Endorsement",
    "Underwater Currency Discovery",
    "Coffee-Powered Blockchain",
    "Teleportation App Release",
    "Temporal Investment Strategy",
    "Invisible Asset Class Emergence",
    "Mind-Reading Financial Advisor Bot",
    "Meme-to-Reality Conversion Technology",
    "Involuntary Dimension Hop",
    "Mood-Based Market Fluctuation",
    "Prosperity Potion Pyramid Scheme",
    "Self-Replicating NFT Crisis",
    "Dream Infiltration Service",
    "Wormhole Transit System Construction",
    "Weather Control Token Launch",
    "Alternate Self Merger Proposal",
    "Currency That Only Exists on Tuesdays",
    "Accidental Resurrection of Ancient Economy",
    "Thought Bubble Visualization Technology",
    "Cryptographic Treasure Map Discovery",
    "Empathy Virus Outbreak",
    "Soul Staking Protocol",
    "Gravity-Defying Asset Bubble",
    "Personality Swap Flash Mob",
    "Musical Number That Never Ends"
] 