# Generated by Django 5.0.3 on 2025-05-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('current_value', models.FloatField(default=0.0)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='api.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='CoinValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_history', to='api.gamecoin')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['coin', 'timestamp'], name='api_coinval_coin_id_865693_idx')],
            },
        ),
    ]
