# Generated by Django 5.0.3 on 2025-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='initial_value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
