# Generated by Django 5.0.3 on 2025-05-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_a_text', models.TextField()),
                ('choice_a_consequence', models.TextField()),
                ('choice_a_new_value', models.FloatField()),
                ('choice_b_text', models.TextField()),
                ('choice_b_consequence', models.TextField()),
                ('choice_b_new_value', models.FloatField()),
                ('selected_choice', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True)),
                ('coin_value_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='api.coinvaluehistory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coin_value_history', 'created_at'], name='api_situati_coin_va_f75452_idx')],
            },
        ),
    ]
