# Generated by Django 5.0.3 on 2025-05-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecoin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamecoin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coin_images/'),
        ),
    ]
