# Generated by Django 5.0.3 on 2025-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecoin',
            name='event_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamecoin',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
