# Generated by Django 5.0.3 on 2025-05-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gamecoin_event_categories_gamecoin_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinvaluehistory',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='gamecoin',
            name='event_categories',
        ),
        migrations.RemoveField(
            model_name='gamecoin',
            name='history',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_a_consequence',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_a_new_value',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_a_text',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_b_consequence',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_b_new_value',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='choice_b_text',
        ),
        migrations.AddField(
            model_name='situation',
            name='choices',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
